sudo: required
language: node_js
node_js:
  - 12
cache: yarn: true
  directories:
    - node_modules
branches:
  only:
    - gh-pages
script:
  - hexo clean
  - hexo generate
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:  
   branch: gh-pages
  local-dir: public